schema_version: 1

context:
  name: opentelemetry-instrumentation-lancedb
  version: "0.62.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_lancedb-${{ version }}.tar.gz
  sha256: acf992d1922c8492f4ed4a8907acc26a1b2cd4feff8aca7bdef48bc37dac03cd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
  run_constraints:
    - lancedb >=0.26.0

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - lancedb
        - pip
    script:
      - python -c "import opentelemetry.instrumentation.lancedb"
      - pip check

about:
  summary: OpenTelemetry Lancedb instrumentation
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://www.traceloop.com/openllmetry
  repository: https://github.com/traceloop/openllmetry
  documentation: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
